FROM node:12-alpine3.12
RUN apk update
RUN apk add --update bash

RUN apk add git
RUN npm install -g --unsafe-perm polymer-cli
RUN npm install -g gulp-cli
RUN npm install -g typescript

WORKDIR /code
CMD ["polymer", "serve"]
